### ISSUE TITLE
Broken hyperlink in text "Learn more about the Advanced View"

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/cloud-manager-relnotes#14]
Page: [Recent changes in Cloud Manager](https://docs.netapp.com/us-en/cloud-manager-relnotes/whats-new.html)

Hi Team,

When I click on the hyperlink below I will get a 404 error. Not sure if that page is a work in progress or if the hyperlink is broken:

![image](https://user-images.githubusercontent.com/80273701/181280917-debb52be-e030-4e6b-a09d-869f8bc57f1f.png)

![image](https://user-images.githubusercontent.com/80273701/181280939-d6a93b51-7450-489f-a66e-4ff5cf568bb3.png)

**Comment by netapp-bcammett** [comment]
@laagabi,

Thank you for catching this issue. I fixed the link.

Thanks again,
Ben
