### ISSUE TITLE
Q: Cloud Manager UI is changed ?

### ISSUE THREAD

**Issue by shinichk** [NetAppDocs/cloud-manager-relnotes#6]
Page: [Cloud Manager release notes](https://docs.netapp.com/us-en/cloud-manager-relnotes/index.html)

Hello, I have a question about Cloud Manager UI. I tried to access to System Manager in CVO Menu. But I couldn't find out System Manager in the menu.  Has there been a change in the Cloud Manager UI ? If so, could you update the manual ?

Best Regards,
Shinichi Kond
![MicrosoftTeams-image](https://user-images.githubusercontent.com/89820074/162652037-eb2cbfc6-2b59-47fa-856a-4efcb1135d95.png)
o

**Comment by netapp-bcammett** [comment]
Shinichi-san,

Thank you for submitting this question. I checked our demo environment and I don't see the System Manager option either. I have reached out to the product team for clarification. I'll let you know what I hear.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Shinichi-san,

I added a note about the removal of System Manager here:
https://docs.netapp.com/us-en/cloud-manager-relnotes/whats-new.html#cloud-volumes-ontap

Thanks,
Ben
